### ISSUE TITLE
Dockerfile uses Flask?

### ISSUE THREAD

**Issue by periwinkleFTW** [app-generator/django-adminkit#2]
3rd line of the dockerfile mentions flask. Why?

**Comment by app-generator** [comment]
Hello @periwinkleFTW,

Being a generated starter the label related to Flask is accidental.  I remove it. 

Let us know if you have issues related to Docker usage.  

P.S. Thank you for using our products

**Comment by periwinkleFTW** [comment]
I do have problems using docker, I can't figure out how you connect to db. In docker-compose it uses 'bridge' setting and I can't figure out what it is. I am trying to hook it up to postgres. Do I just change the settings.py?

**Comment by app-generator** [comment]
Please describe in deep what's wrong.
OS version, commands you're executing plus other things that might help us.

Ty!
