### ISSUE TITLE
Makemigrations error

### ISSUE THREAD

**Issue by CraftedCat** [app-generator/django-adminkit#8]
Hi, guys!

Windows 10 x64
Python 3.7

When i try make migrations, catch error:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
No changes detected

**Comment by app-generator** [comment]
Hello @CraftedCat, 

Thank you for using our products. 

The routing file should be updated to remove the rule for `admin` - no slash at the end.

**Comment by CraftedCat** [comment]
I think the problem is still in the duplication of strings.

 path('admin/', admin.site.urls),          # Django admin route
 path('admin' , admin.site.urls),          # Django admin route 

And right is - admin/

**Comment by app-generator** [comment]
Hello,

Your assumption is correct.
Please update the routing file by removing the line *"path('admin' ,
admin.site.urls)" *

Let us know if you need further assistance.
